### ISSUE TITLE
Victory Bug

### ISSUE THREAD

**Issue by VonHarley** [2michellen/SupermarketShowdown#5]
Even if all objects are acquired, the player always loses.

**Comment by asterwnie** [comment]
I assume this is for the "InstantEat" version of the game - I accidentally forgot to re-attach the objectives to the player! I've adjusted it so you get the end screen once you've collected them all now. I posted the new one here: (File is called SupermarketShowdown1-30-21InstantEatFixed) https://github.com/2michellen/SupermarketShowdown/releases/tag/prealpha-v0.0.4
